[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
cnfg = { path = "../../crates/cnfg" }

# serde + formats
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# extra crates used by validators
regex = "1"
url = "2"
